#!/usr/bin/env python3
"""
Generate damage-state art variants for enemy characters via Gemini img2img
anchored to the enemy's clean base texture. Replaces simple red-tint
placeholders with real per-enemy thematic injury art.

Output path (mirrors dev_menu's variant lookup):
    res://assets/textures/variants/enemies/{enemy_id}/{enemy_id}_state{N}_{name}.png

States generated (state 0 = healthy = the clean base, no generation needed):
    1 = hurt    (>33% and <66% HP) — light damage
    2 = injured (>10% and <33% HP) — moderate wounds
    3 = dying   (<10% HP)          — critical / dramatic

Each enemy has a unique thematic injury style — NOT all the same generic
"add bandages" prompt. Crumbling bread, split sausage, shattering bottle, etc.

Inputs (env):
    ENEMY_ID        e.g. "basic", "cervelat" (or "all" to run all)
    GEMINI_API_KEY  required (primary provider)
    STABILITY_API_KEY  optional fallback
"""
from __future__ import annotations

import os
import pathlib
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generators import call_gemini_img2img, call_stability_img2img  # noqa: E402


# enemy_id → path to clean base PNG (relative to repo root)
# Entries for new enemies point to paths that art-request issues #333-343 will create.
ENEMY_BASES: dict[str, str] = {
    # Original 6 — base textures already exist
    "basic":         "assets/textures/enemies/brotli_clean.png",
    "fast":          "assets/textures/enemies/toblerone_clean.png",
    "tank":          "assets/textures/enemies/cervelat_clean.png",
    "healer":        "assets/textures/enemies/rivella_clean.png",
    "flying":        "assets/textures/enemies/fondue_clean.png",
    "boss":          "assets/textures/enemies/mteufel_clean.png",
    # New 11 — base textures generated by art-request issues #333-343
    "camo":          "assets/textures/enemies/camo_clean.png",
    "lead":          "assets/textures/enemies/lead_clean.png",
    "regrow":        "assets/textures/enemies/regrow_clean.png",
    "swarm":         "assets/textures/enemies/swarm_clean.png",
    "fondue_bomb":   "assets/textures/enemies/fondue_bomb_clean.png",
    "glace_golem":   "assets/textures/enemies/glace_golem_clean.png",
    "berserker":     "assets/textures/enemies/berserker_clean.png",
    "cumulus_blob":  "assets/textures/enemies/cumulus_blob_clean.png",
    "linsen_golem":  "assets/textures/enemies/linsen_golem_clean.png",
    "smoothie_slime":"assets/textures/enemies/smoothie_slime_clean.png",
    "tofu_ninja":    "assets/textures/enemies/tofu_ninja_clean.png",
}

# Per-enemy chibi style base (prepended to every damage prompt)
ENEMY_BASE_PERSONA: dict[str, str] = {
    "basic": (
        "cute chibi cartoon bread roll character (Wüetende Tofu-Würschtli), "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "fast": (
        "cute chibi cartoon Toblerone chocolate bar character (Turbo Hafer-Riegel), "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "tank": (
        "cute chibi cartoon Swiss sausage (Cervelat) character, tough and armored, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "healer": (
        "cute chibi cartoon Rivella drink bottle character with a friendly nurse aura, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "flying": (
        "cute chibi cartoon fondue pot character with stubby wings, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "boss": (
        "cute chibi cartoon vegan devil (M-Tüufel) with horns and torn cape, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "camo": (
        "cute chibi cartoon camouflaged tofu block character (Schatte-Tofu), "
        "dark blue-gray with shadow patterns, wearing a tiny ninja scarf, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "lead": (
        "cute chibi cartoon armored tin can character (Büchse-Brätzeli), "
        "metallic gray with rivets, bulky and tank-like, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "regrow": (
        "cute chibi cartoon kamikaze croissant character (Kamikaze-Gipfeli), "
        "golden-brown flaky pastry, wearing a red kamikaze headband, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "swarm": (
        "cute chibi cartoon tiny tofu cube character (Tofu-Schwarm), "
        "very small creamy-white block with a tiny angry mob face, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "fondue_bomb": (
        "cute chibi cartoon fondue pot bomb character (Fondue-Bomb), "
        "golden-orange ceramic pot with bubbling cheese and a lit fuse, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "glace_golem": (
        "cute chibi cartoon ice cream golem character (Glacé-Golem), "
        "built from stacked gelato scoops with a wafer cone helmet and tiny wings, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "berserker": (
        "cute chibi cartoon seitan berserker character (Seitän-Berserker), "
        "dark crimson red body, bulging veins, wild rage expression, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "cumulus_blob": (
        "cute chibi cartoon pink gelatin blob character (Cumulus-Blob), "
        "wobbly round pudding body, soft pastel pink, iridescent edges, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "linsen_golem": (
        "cute chibi cartoon lentil golem character (Linsen-Golem), "
        "enormous olive-green body built from compressed lentils, massive and slow, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "smoothie_slime": (
        "cute chibi cartoon green smoothie slime character (Grüene Smoothie-Schleim), "
        "viscous neon-green body with kale and spinach visible inside, glossy surface, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
    "tofu_ninja": (
        "cute chibi cartoon tofu ninja character (Tofu-Ninja), "
        "white tofu block in dark navy ninja outfit with mask and sesame-seed throwing stars, "
        "Pixar-style, 1:1 square, transparent background, centered"
    ),
}

# Per-enemy damage state prompts — creative and thematic, NOT generic
DAMAGE_PROMPTS: dict[str, dict[str, str]] = {
    "basic": {
        "hurt":    "light hurt state: a small bite taken out of the top, crumbs scattered around feet, slightly surprised expression, warm bread interior visible at the bite",
        "injured": "injured state: big chunk bitten off the side, jam or cream filling oozing out, squashed a little flat, crumbs everywhere, worried expression, small bandage sticker on the bite",
        "dying":   "critical dying state: barely a quarter of the bread roll remains, burnt blackened crust edges, crumbling in real time with crumb particles flying off, desperate wide eyes, the remaining bit trembling",
    },
    "fast": {
        "hurt":    "light hurt state: wrapper slightly torn at corner, one chocolate triangle chipped off, a smear of melted chocolate on the edge, still smirking but nervous",
        "injured": "injured state: half the wrapper ripped off and melting, multiple triangles broken, liquid chocolate dripping down sides, melting expression, one eye squinting in pain",
        "dying":   "critical dying state: nearly fully melted into a glossy puddle, wrapper in shreds, desperately holding its face shape above a molten chocolate base, horrified eyes, last few solid pieces crumbling",
    },
    "tank": {
        "hurt":    "light hurt state: a small split seam on one side with sausage skin curling outward, tiny grease bead forming, still stoic but flinching",
        "injured": "injured state: big X-shaped crack split across the belly with filling oozing out in two streams, skin peeling back, grimacing hard, internal stuffing visible and steaming",
        "dying":   "critical dying state: completely burst open from both ends, filling erupting outward like a disaster, skin hanging off in strips, held together by sheer stubbornness, smoke rising from the cracks",
    },
    "healer": {
        "hurt":    "light hurt state: small dent in the bottle, label edge peeling up, a thin trickle of liquid running down from a hairline crack, still smiling but visibly stressed",
        "injured": "injured state: bottle cracked in two places with liquid spraying sideways, label torn and hanging, the cap askew and leaking, desperate expression, liquid forming a puddle at base",
        "dying":   "critical dying state: bottle shattering — held together only by surface tension and willpower, glass cracks radiating everywhere, liquid erupting outward in a spray, eyes wide in panic, barely intact",
    },
    "flying": {
        "hurt":    "light hurt state: cheese has cooled and hardened along the rim, a small crack in the ceramic pot, stubby wings drooping a little, slightly cold expression",
        "injured": "injured state: pot cracked across the side with cheese erupting like a mini-volcano, steam billowing, one wing singed and bent, grimacing, cheese dripping off the edges in long strings",
        "dying":   "critical dying state: pot tipped at a 45-degree angle, half the fondue spilled and solidifying in a lava flow, one wing completely gone, pot rim shattered, one desperate eye looking up from the wreckage",
    },
    "boss": {
        "hurt":    "light hurt state: a crack running up one horn, small tear in the cape, eye twitching with barely-contained rage, knuckles clenched",
        "injured": "injured state: both horns chipped and cracked, face marked with glowing wounds, wings damaged with holes, cape tattered, radiating dark energy but visibly weakened, snarling through gritted teeth",
        "dying":   "critical dying state: full demonic desperation — horns shattered to stumps, face split with magical wounds glowing red, wings disintegrating, dark energy explosions all around, screaming in fury and fear, last-stand aura",
    },
    "camo": {
        "hurt":    "light hurt state: the camouflage flickering — briefly visible, a small scorch mark on the tofu surface, one glowing eye wide in alarm, partially solid and partially ghost-transparent",
        "injured": "injured state: camouflage failing completely in large patches, tofu cracking and glowing where wounded, desperately trying to re-vanish but unable, panicked expression, dark aura destabilizing wildly",
        "dying":   "critical dying state: all stealth shattered — fully visible and terrified, tofu shattering into semi-transparent fragments, ninja scarf tattered, last desperate attempt to disappear as the body disintegrates into shadow-smoke",
    },
    "lead": {
        "hurt":    "light hurt state: a small dent in the metallic plating, one rivet popped out, label corner torn, still stoic and armored but flinching slightly, tiny crack in the tin",
        "injured": "injured state: deep gashes in the tin armor, one side crumpled inward, Brätzeli biscuits spilling out from the damage, grimacing hard, metal peeling back from the wounds, steam escaping",
        "dying":   "critical dying state: tin can catastrophically crushed and burst open from all sides, Brätzeli showering everywhere, metal armor in shreds, label completely destroyed, barely recognizable as a can anymore",
    },
    "regrow": {
        "hurt":    "light hurt state: corner of the croissant bitten off, flaky pastry layers crumbling at the edges, headband still on, still grinning but with fresh bite marks and crumbs falling",
        "injured": "injured state: half the croissant torn away but already visibly REGROWING — new golden pastry layers forming at the wound edges, one arm missing but a stub growing back, defiant smile despite injury",
        "dying":   "critical dying state: reduced to just a tiny sliver but frantically regenerating — ghost outline of the full body visible as it tries desperately to grow back, only a quarter remains, racing against time with terrified but stubborn expression",
    },
    "swarm": {
        "hurt":    "light hurt state: a small corner chipped off the tofu cube, tiny crack running across the surface, miniature tofu cube looking extremely offended and outraged",
        "injured": "injured state: cracked in two nearly-equal halves but still held together somehow, tofu liquid oozing at the split, the two halves wobbling independently but still fighting",
        "dying":   "critical dying state: crumbled into a cluster of tiny tofu crumbs, each individual crumb still has tiny angry eyes, the main body barely recognizable, falling apart in slow motion",
    },
    "fondue_bomb": {
        "hurt":    "light hurt state: one side of the ceramic pot cracked with a thin cheese stream leaking, fuse slightly shorter and sparking more, grimacing at the damage but still smirking dangerously",
        "injured": "injured state: the pot cracked in two places with cheese erupting in a mini-explosion upward, the bomb-shaped body tilted and damaged, fuse nearly burned down, wild panicked eyes",
        "dying":   "critical dying state: the fondue pot DETONATING — cheese eruption in all directions like a volcanic explosion, ceramic shards flying outward, the body shattered into a golden cheese cloud, eyes wide in a final scream",
    },
    "glace_golem": {
        "hurt":    "light hurt state: one ice cream scoop melting and drooping to one side, tiny wings singed and drooping, a trickle of ice cream melting down the body, grimacing from the warmth",
        "injured": "injured state: half the gelato body melted into a sticky pool at the base, the wafer cone helmet cracked, wings severely damaged and barely functioning, struggling to stay airborne, desperate expression",
        "dying":   "critical dying state: almost fully melted — just the wafer cone helmet remains intact above a spreading gelato puddle, wings useless and melted, one last pair of eyes looking up from the melted mass in disbelief",
    },
    "berserker": {
        "hurt":    "light hurt state: a deep gash across the seitan body with wheat-fiber insides exposed, this only makes it MORE angry — wider eyes, extra rage aura, clenched teeth intensifying, even more berserk",
        "injured": "injured state: massive damage with wheat gluten fibers tearing apart, wounds glowing red with rage energy, still standing and even MORE berserk — shaking violently, berserker aura doubled in size",
        "dying":   "critical dying state: body nearly destroyed but still fighting — held together by pure seitan protein strands hanging by threads, radiating a FINAL RAGE burst, screaming at full volume, entire frame crumbling in an explosion of rage energy and wheat fibers",
    },
    "cumulus_blob": {
        "hurt":    "light hurt state: a small chunk jiggled off the blob, the main body wobbling violently from impact, slightly deflated on one side, startled and surprised expression (not angry, just very jiggly)",
        "injured": "injured state: blob split into two connected wobbling lobes, iridescent inner liquid splashing around, desperately trying to re-cohere into one shape, frantic jelly expression",
        "dying":   "critical dying state: blob splattered nearly flat like spilled jello, final form spreading outward in a thin quivering sheet, tiny eyes in the center looking up hopelessly as the last bit of coherence dissolves",
    },
    "linsen_golem": {
        "hurt":    "light hurt state: a chunk of lentils knocked off one shoulder, small crater visible in the lentil-textured body, individual lentils scattered around feet, unimpressed and barely noticing",
        "injured": "injured state: major sections of the lentil body blasted away, lentils raining down like gravel, structural cracks running through the golem body, beginning to stagger but still enormous, confused at being hurt",
        "dying":   "critical dying state: the lentil golem CRUMBLING — cascading structural failure, lentils avalanching off in massive chunks, towering body collapsing inward, eyes expressing shocked disbelief that it could be stopped",
    },
    "smoothie_slime": {
        "hurt":    "light hurt state: a section of the slime body scorched and discolored, burnt kale visible at the wound, acrid green smoke rising, the slime recoiling from the heat in disgust",
        "injured": "injured state: slime body split into two pools connected by a narrow bridge, green smoothie contents partially separated — banana on one side, spinach on the other, glowing internal energy destabilizing",
        "dying":   "critical dying state: slime evaporating — body reduced to a thin ring outline barely visible, green vapor rising upward, the ingredients (kale, banana, chia) suspended mid-air as the liquid form vanishes",
    },
    "tofu_ninja": {
        "hurt":    "light hurt state: ninja mask torn at the corner revealing one panicked eye, a throwing star knocked from the hand, crouched lower into a defensive stance, dark shadow aura flickering",
        "injured": "injured state: ninja uniform tattered and torn, tofu body cracking across the middle, shadow aura destabilizing and sparking, one hand clutching the wound, trying to maintain stealth but clearly failing",
        "dying":   "critical dying state: ninja stealth completely shattered — fully visible and falling, tofu body shattering into white cubes, uniform in shreds, throwing stars scattered everywhere, making one final desperate throw as the body disintegrates",
    },
}

STATE_NAMES = ["hurt", "injured", "dying"]
STATE_NUMBERS = [1, 2, 3]


def log(msg: str) -> None:
    print(f"[enemy_damage_variants] {msg}", flush=True)


def generate_for_enemy(enemy_id: str) -> list[str]:
    base_path_str = ENEMY_BASES.get(enemy_id)
    if not base_path_str:
        log(f"no base texture registered for '{enemy_id}' — skipping")
        return []

    base_photo = pathlib.Path(base_path_str)
    if not base_photo.exists():
        log(f"base texture not found: {base_photo} — skipping {enemy_id}")
        return []

    persona = ENEMY_BASE_PERSONA.get(enemy_id, "cute chibi cartoon character, Pixar-style, 1:1 square, transparent background")
    state_prompts = DAMAGE_PROMPTS.get(enemy_id, {})

    out_dir = pathlib.Path(f"assets/textures/variants/enemies/{enemy_id}")
    out_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for state_num, state_name in zip(STATE_NUMBERS, STATE_NAMES):
        state_prompt = state_prompts.get(state_name)
        if not state_prompt:
            log(f"no prompt for {enemy_id}/{state_name} — skipping")
            continue

        out_path = out_dir / f"{enemy_id}_state{state_num}_{state_name}.png"
        full_prompt = f"{persona}. Damage state: {state_prompt}"

        log(f"=== {enemy_id} state{state_num}_{state_name} ===")
        log(f"prompt: {full_prompt[:140]}...")

        if call_gemini_img2img(base_photo, full_prompt, out_path):
            written.append(str(out_path))
            log(f"wrote {out_path}")
        elif call_stability_img2img(base_photo, full_prompt, out_path):
            written.append(str(out_path))
            log(f"wrote {out_path} (stability fallback)")
        else:
            log(f"both providers failed for {out_path} — skipping")

    return written


def main() -> int:
    target = os.environ.get("ENEMY_ID", "").strip().lower()

    if target == "all" or target == "":
        enemies_to_run = list(ENEMY_BASES.keys())
    elif target in ENEMY_BASES:
        enemies_to_run = [target]
    else:
        log(f"unknown ENEMY_ID '{target}'. Known: {sorted(ENEMY_BASES)}")
        return 1

    all_written: list[str] = []
    for enemy_id in enemies_to_run:
        written = generate_for_enemy(enemy_id)
        all_written.extend(written)

    if not all_written:
        log("nothing generated — both providers failed for all enemies/states")
        return 1

    out_file = os.environ.get("GITHUB_OUTPUT")
    if out_file:
        with open(out_file, "a") as f:
            f.write(f"asset_paths={','.join(all_written)}\n")
            f.write(f"count={len(all_written)}\n")
            f.write(f"enemy_ids={','.join(enemies_to_run)}\n")

    log(f"total: {len(all_written)} variant(s) written: {all_written}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
